command_type: system
ignore:
    - "*.py"
    - "*.sh"
    - "*.md"

variables:
  - &run-test
    name: test
    commands:
      - command: git.get_project
        params:
          directory: gopath/src/github.com/evergreen-ci/logkeeper
      - func: run-make
        vars: { target: "${task_name}" }
  - &run-test-mongodb
    # runs a make target above, but only on systems that have a
    # running mongod started for testing.
    name: test
    commands:
      - command: git.get_project
        params:
          directory: gopath/src/github.com/evergreen-ci/logkeeper
      - func: set-up-mongodb
      - func: run-make
        vars: { target: "${task_name}" }

functions:
  run-make:
    command: shell.exec
    type: test
    params:
       script: |
         set -o errexit
         set -o verbose

         # Configure a local go path for this build.
         export GOPATH=`pwd`/gopath

         # on windows we need to turn the slashes the other way
         if [ "Windows_NT" == "$OS" ]; then
            export GOPATH=$(cygpath -m $GOPATH)
         fi

         cd gopath/src/github.com/evergreen-ci/logkeeper

         # Run make, called with proper environment variables set,
         # running the target.
         ${build_env} make ${make_args|} vendor ${target}
  set-up-mongodb:
    - command: shell.exec
      params:
        script: |
          set -o errexit
          set -o verbose

          rm -rf mongodb
          mkdir mongodb
          cd mongodb
          curl ${mongodb_url} -o mongodb${archiveExt|.tgz}

          ${decompress} mongodb${archiveExt|.tgz}
          chmod +x ./mongodb-*/bin/*
          mv ./mongodb-*/bin/* .
          rm -rf db_files
          rm -rf db_logs
          mkdir db_files
          mkdir db_logs
    - command: shell.exec
      params:
        background: true
        script: |
          set -o errexit
          set -o verbose

          cd mongodb
          echo "starting mongod..."
          ./mongod${extension|} --dbpath ./db_files &
          echo "waiting for mongod to start up"
    - command: shell.exec
      params:
        script: |
          set -o errexit
          set -o verbose

          cd mongodb
          ./mongo${extension|} --nodb --eval 'assert.soon(function(x){try{var d = new Mongo("localhost:27017"); return true}catch(e){return false}}, "timed out connecting")'
          echo "mongod is up."


tasks:
  - name: dist
    tags: ["dist"]
    commands:
      - command: git.get_project
        params:
          directory: gopath/src/github.com/evergreen-ci/logkeeper
      - func: run-make
        vars: { target: "dist" }
      - command: s3.put
        params:
          aws_key: ${aws_key}
          aws_secret: ${aws_secret}
          local_file: gopath/src/github.com/evergreen-ci/logkeper/bin/${task_name}.tar.gz
          remote_file: logkeeeper/${build_id}-${build_variant}/logkeeper-${task_name}-${revision}.tar.gz
          bucket: mciuploads
          content_type: application/x-gzip
          permissions: public-read
          display_name: dist.tar.gz
  - name: coverage
    tags: [ "report" ]
    commands:
      - command: git.get_project
        params:
          directory: gopath/src/github.com/evergreen-ci/logkeeper
      - func: set-up-mongodb
      - func: run-make
        vars:
          target: "coverage-html"
          make_args: "-k"
      - command: s3.put
        params:
          aws_key: ${aws_key}
          aws_secret: ${aws_secret}
          local_files_include_filter: ["gopath/src/github.com/evergreen-ci/logkeeper/bin/output.*.coverage.html"]
          remote_file: logkeeper/${task_id}/
          bucket: mciuploads
          content_type: text/html
          permissions: public-read
          display_name: "(html) coverage:"
      - command: s3.put
        params:
          aws_key: ${aws_key}
          aws_secret: ${aws_secret}
          local_files_include_filter: ["gopath/src/github.com/evergreen-ci/logkeeper/bin/output.*.coverage"]
          remote_file: logkeeper/${task_id}/
          bucket: mciuploads
          content_type: text/plain
          permissions: public-read
          display_name: "(txt) coverage:"
  - <<: *run-test
    name: lint
    tags: ["report"]
  - <<: *run-test-mongodb
    name: test-logkeeper
    tags: ["test"]
  - <<: *run-test-mongodb
    name: race-logkeeper
    tags: ["race"]

post:
  - command: gotest.parse_files
    params:
      files:
        - "gopath/src/github.com/evergreen-ci/logkeeper/build/test.*.out"
        - "gopath/src/github.com/evergreen-ci/logkeeper/build/race.*.out"


buildvariants:
  - name: rhel62-gccgo
    display_name: RHEL 6.2 (gccgo)
    expansions:
      build_env: "PATH=/opt/mongodbtoolchain/v2/bin:$PATH DISABLE_COVERAGE=yes"
      mongodb_url: http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.2.6.tgz
    run_on:
      - rhel62-small
    tasks:
      - ".dist"
      - ".test"

  - name: rhel70
    display_name: RHEL 7.0
    expansions:
      build_env: "PATH=/opt/go:$PATH"
      mongodb_url: http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.2.6.tgz
    run_on:
      - rhel70-small
      - rhel70
    tasks:
      - ".dist"
      - ".test"

  - name: race-detector
    display_name: Race Detector (Arch Linux)
    expansions:
      mongodb_url: http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.2.6.tgz
    run_on:
      - archlinux-test
      - archlinux-build
    tasks:
      - ".race"
      - ".report"

  - name: osx
    display_name: OS X 10.10
    expansions:
      build_env: "PATH=/usr/local/go/bin:$PATH"
      mongodb_url: http://fastdl.mongodb.org/osx/mongodb-osx-x86_64-3.2.6.tgz
    run_on:
      - osx-1010
    tasks:
      - ".dist"
      - ".test"
